# Generated by Django 4.0.1 on 2022-02-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_tag_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.tag'),
        ),
    ]
