# Generated by Django 4.0.1 on 2022-03-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slider_posts',
            field=models.BooleanField(default=False),
        ),
    ]
