# Generated by Django 4.0.1 on 2022-03-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birt_day',
            new_name='birth_day',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='users/200x200.png', max_length=250, null=True, upload_to='users'),
        ),
    ]
